In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('wine_data_cleaned.csv')
df.head()

             Title               Grape Location  Rating  Price  Year
0  Angélica Zapata              malbec  Mendoza     4.6   3700  2015
1      D.V. Catena              malbec  Mendoza     4.4   2250  2016
2       Viña Cobos              malbec  Mendoza     4.0   1155  2018
3      D.V. Catena              malbec  Mendoza     4.3   3200  2012
4       Viña Cobos  cabernet sauvignon  Mendoza     4.0   1155  2017

In [4]:
df = pd.get_dummies(df, columns = ['Grape'], prefix='', prefix_sep='')

In [6]:
df.head()

,Title,Location,Rating,Price,Year,blend,bonarda,cabernet franc,cabernet sauvignon,malbec,other
0,Angélica Zapata,Mendoza,4.6,3700,2015,0,0,0,0,1,0
1,D.V. Catena,Mendoza,4.4,2250,2016,0,0,0,0,1,0
2,Viña Cobos,Mendoza,4.0,1155,2018,0,0,0,0,1,0
3,D.V. Catena,Mendoza,4.3,3200,2012,0,0,0,0,1,0
4,Viña Cobos,Mendoza,4.0,1155,2017,0,0,0,1,0,0